### ISSUE TITLE
member name en surname combineren

### ISSUE THREAD

**Issue by Demivdm** [zombie0youssra/zombie0youssra-profile-card#3]
Je kunt de code iets korter maken door <h2>member.name + "" + member.surname </h2> te gebruiken.

https://github.com/zombie0youssra/zombie0youssra-profile-card/blob/a4f0b38a6c17390d441a4f9e9c493e861c9e6d11/views/index.ejs#L16

**Comment by zombie0youssra** [comment]
thanks ga het gebruiken
