### ISSUE TITLE
Definitions of done! 😊

### ISSUE THREAD

**Issue by Nazneen05x** [zombie0youssra/zombie0youssra-profile-card#4]
**- Is het eindresultaat gedocumenteerd in wiki aan de hand van de DLC?**
Je hebt al een mooi begin gemaakt, nu nog alleen vullen met inhoud!
**- Is het kaartje gepubliceerd via cyclic.sh?**
Je url naam past echt bij jou! ahhaah 😊
**- Gebruik het kaartje gegevens uit de rest api op whois.fdnd.nl**
Dit is al besproken met docenten en met elkaar!
**- Is het visitekaartje gemaakt met node?**
<img width="1358" alt="Schermafbeelding 2023-02-10 om 10 42 05" src="https://user-images.githubusercontent.com/112861261/218058391-6eec2338-7814-4007-a868-f93a94ee4952.png">
<img width="1365" alt="Schermafbeelding 2023-02-10 om 10 42 15" src="https://user-images.githubusercontent.com/112861261/218058427-3b7befc7-6fdc-45b2-8c04-4c7d378698ab.png">

**Comment by zombie0youssra** [comment]
its is done
